[package]
name = "rust_invaders"
version = "0.1.0"
authors = ["Jason Jarvis <jazzay@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = "0.15.0"
winit = "0.22.2"
